service: vpc-aurora-sql
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment: 
    MYSQL_HOST: ${env:MYSQL_HOST, "serverless-course.cluster-c6hyzdsc4gew.us-east-1.rds.amazonaws.com"}
    MYSQL_PORT: ${env:MYSQL_PORT, "3306"}
    MYSQL_USER: ${env:MYSQL_USER, "hellshi"}
    MYSQL_PASS: ${env:MYSQL_PASS, "jh62mg21-dr"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "heroes"}

plugins: 
  - serverless-offline

package:
  excludeDevDependencies: true

functions:
  function1:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: hello