service: vpc-aurora-sql
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment: 
    MYSQL_HOST: ${env:MYSQL_HOST, "your db host"}
    MYSQL_USER: ${env:MYSQL_USER, "your user"}
    MYSQL_PASS: ${env:MYSQL_PASS, "your pass"}
    MYSQL_PORT: ${env:MYSQL_PORT, "3306"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "heroes"}

plugins: 
  - serverless-offline

package:
  excludeDevDependencies: true

functions:
  function1:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: hello